/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE examBase PLEASE EDIT ../exam.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Classe } from '../classe';
import { Exam } from '../exam';
import { Professeure } from '../professeure';

/**
 * This is the model of exam object
 *
 */
export class ExamBase {

    constructor() { }

    public _id: string;
    public classe?: number;
    public date?: Date;
    public nom_exam?: number;
    public professor?: number;
    // Relations class_exam
    public class_exam: Classe | string;
    // Relations nom_exam
    public nom_exam: Exam | string;
    // Relations prof_exam
    public prof_exam: Professeure | string;
}
